{{- if not .Values.vergeos.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vergeos-csi.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  VERGEOS_HOST: {{ .Values.vergeos.host | quote }}
  VERGEOS_API_KEY: {{ .Values.vergeos.apiKey | quote }}
  VERGEOS_VERIFY_SSL: {{ .Values.vergeos.verifySSL | quote }}
{{- end }}
